# Generated by Django 2.2.1 on 2019-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_price', models.TextField()),
                ('prod_quan', models.IntegerField()),
                ('img_link', models.TextField()),
            ],
        ),
    ]
